### ISSUE TITLE
Leggibilità product state

### ISSUE THREAD

**Issue by andreatosato** [gaspa85/unitTestExercises#1]
Questa riga mi ha lasciato perplesso sulla leggibilità.
La trovo difficile da mantenere, perchè sto specificando una chiave temporale e sto imponendo all'interno del product state un secondo range di date.
```cs
    public Dictionary<TimeRange, ProductState> MapProductState = new Dictionary<TimeRange, ProductState>();
```

Penso sia più corretto vedere il prodotto come lo stato corrente.
ProductHistory come lo storico dello stato del prodotto. 
Sono due entità che dovrebbero essere mantenute distinte.

**Comment by gaspa85** [comment]
ho capito, chiaro lo applico

**Comment by gaspa85** [comment]
l'ho modificato, ho pensato di tenere l'informazione TimeRange all'interno del ProductState e trasformare il Dictionary in list

`public List<ProductState> ListProductState { get; set; } = new List<ProductState>();`
